version: "3.5"

services:
  php:
    build:
      context: ./php
      args:
        UID: "${UID}"
        GID: "${GID}"
    volumes:
      - ${LOCAL_SOCKET_PATH}:${CONTAINER_SOCKET_PATH}
      - ${LOCAL_SRC_ROOT}:${CONTAINER_SRC_ROOT}
      - ./php/conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./php/conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./php/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - ${INTERFACE}:${DEBUG_HOST_MACHINE_PORT}:9000
    networks:
      - inner
    links:
      - db
  nginx:
    build:
      context: ./nginx
      args:
        UID: "${UID}"
        GID: "${GID}"
    volumes:
      - ./nginx/logs:/var/log/nginx/
      - ${LOCAL_SOCKET_PATH}:${CONTAINER_SOCKET_PATH}
      - ${LOCAL_SRC_ROOT}:${CONTAINER_SRC_ROOT}
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '${INTERFACE}:80:80'
      - '${INTERFACE}:443:443'
    depends_on:
      - php
    links:
      - php
    networks:
      - inner
  db:
    build: ./mysql
    platform: linux/amd64
    ports:
      - '${INTERFACE}:3306:3306'
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: mysqld --sql-mode=""
    networks:
      - inner
    restart: always
  adminer:
    image: dockette/adminer:full
    links:
      - db:db
    ports:
      - '${INTERFACE}:8080:80'
    environment:
      UPLOAD: 1024M # upload_max_filesize, post_max_size
    networks:
      - inner

networks:
    inner:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: ${SUBNET}
